### ISSUE TITLE
LyZ does not respond

### ISSUE THREAD

**Issue by jingyangyzby** [wshanks/lyz#38]
The LYZ suddenly stops working. After creating the Lyx file, selecting one reference in Zotero, and clicking the button LYZ, the following window pops out 
<img width="475" alt="Capture d’écran 2021-09-05 à 1 29 00 PM" src="https://user-images.githubusercontent.com/29261103/132125103-47ec423e-ed9c-43e7-9ed9-fddf8ae26178.png">

However, when I click either cancel or ok, the window disappears and there are no further reminders. Interesting, I can still insert references to my old .lyx files through LYZ as if it is normal. I understand for old .lyx files LYZ already knows it. It seems now LYZ stops recognize any new .lyx files? Does anybody have any clues about what has happened?.  Thanks in advance!
<img width="599" alt="Capture d’écran 2021-09-05 à 1 33 56 PM" src="https://user-images.githubusercontent.com/29261103/132125214-7fdf8ecf-a4b3-4462-a4e7-4a6b5828f655.png">

**Comment by wshanks** [comment]
Thanks for the report. I created a fix for this in #39.
